name: Test Documentation

on: [push]




jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install OS dependencies
        run: |
          sudo apt-get -y make enchant-2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt -c constraints.txt
      - name: Run Link-Check
        run: |
          make linkcheck
      - name: Run Spell-Check
        run: |
          make spelling



